### ISSUE TITLE
Bug: Library cannot delete nodes contrary to documentation

### ISSUE THREAD

**Issue by hq6** [pantoniou/libfyaml#115]
This issue can be mitigated run applying this patch:
```
diff --git a/src/lib/fy-doc.c b/src/lib/fy-doc.c
index 0032ee4..de0fbc1 100644
--- a/src/lib/fy-doc.c
+++ b/src/lib/fy-doc.c
@@ -2224,8 +2224,8 @@ int fy_node_insert(struct fy_node *fyn_to, struct fy_node *fyn_from)
 		fyd_error_check(fyd, fyn_parent->type != FYNT_SCALAR, err_out,
 				    "Illegal scalar parent node type");
 
-		fyd_error_check(fyd, fyn_from, err_out,
-				"Illegal NULL source node");
+//		fyd_error_check(fyd, fyn_from, err_out,
+//				"Illegal NULL source node");
 
 		if (fyn_parent->type == FYNT_MAPPING) {
 			/* find mapping pair that contains the `to` node */
```

**Comment by pantoniou** [comment]
Err, what is an example source snippet where this happens?

**Comment by hq6** [comment]
Consider the following YAML file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    x: 2024-06-12t14:50:43z

```
Consider the following C source file:
```
#include <stdlib.h>
#include <stdio.h>

#include <libfyaml.h>

int main(int argc, char *argv[])
{
	struct fy_document *fyd = NULL;
  fyd = fy_document_build_from_file(NULL, argv[1]);
  fy_document_insert_at(fyd, "/metadata/annotations/x", FY_NT, NULL);
  fy_emit_document_to_fp(fyd, FYECF_DEFAULT, stdout);
}
```
Here is the result when I run it without the patch:


```
~/Code/YamlPlay main * ./MWE MWE.yaml
[ERR]: Illegal NULL source node
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    x: 2024-06-12t14:50:43z
```

Here is the result when I run it with the patch:
```
~/Code/YamlPlay main * ./MWE MWE.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
```

The [documentation](https://pantoniou.github.io/libfyaml/libfyaml.html#fy-document-insert-at-description) for that function claims the following:

> Insert a node to a given point in the document. If fyn is NULL then this operation will delete the target node.
